name: "Build latest docker"
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup JDK"
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: "Build shadowJar"
        env:
          JAVA_HOME: ${{ steps.java.outputs.path }}
        run: |
          chmod u+x ./gradlew
          ./gradlew clean shadow-ci -Pvaadin.productionMode
      - name: Upload shadowJar artifact
        uses: actions/upload-artifact@v4
        with:
          name: "executable-jar"
          path: build/libs/*-all.jar
      - name: "Clean gradlew"
        env:
          JAVA_HOME: ${{ steps.java.outputs.path }}
        run: ./gradlew clean
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "."
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USER }}/styx-web:latest
      - name: "Update description"
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ vars.DOCKER_USER }}/styx-web